<?php

namespace DannyXCII\EnvironmentManager\Classes\Command\Commands;

use DannyXCII\EnvironmentManager\Classes\Command\Command;
use DannyXCII\EnvironmentManager\Enums\CommandStatus;
use DannyXCII\EnvironmentManager\Interface\RunnableCommandInterface;

final class Start extends Command implements RunnableCommandInterface
{
    protected function initialize()
    {
        $this->requiredArguments = ['name'];

        parent::initialize(); // TODO: Change the autogenerated stub
    }

    public function run(): CommandStatus
    {
        if (!$this->options->get('name')) {
            $this->writer->addError('Please specify the name of the container you wish to start.');

            return CommandStatus::Error;
        }

        return CommandStatus::Success;
    }
}